=== thia-thia/schema/stud.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence> 
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="age" type="xs:string" />
                            <xs:element name="course">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z\s]{3,30}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="address" type="xs:string" minOccurs="0" />
                            <xs:element name="phone">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{10}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dob" type="xs:date" />
                            <xs:element name="Jyear" type="xs:gYear" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== thia-thia/schema/stud_exsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="stud.xsd">
        <student id="1">
            <name>Sakthi</name>
            <age>20</age>
            <course>IT</course>
            <address>Madurai</address>
            <phone>9751423916</phone>
            <dob>2004-11-23</dob>
            <Jyear>2022</Jyear>
        </student>
        <student id="2">
            <name>Roshini</name>
            <age>19</age>
            <course>ECE</course>
            <phone>9940467525</phone>
            <dob>2005-09-08</dob>
            <Jyear>2023</Jyear>
        </student>
        <student id="3">
            <name>Harshi</name>
            <age>19</age>
            <course>CSE</course>
            <address>Coimbatore</address>
            <phone>9444901665</phone>
            <dob>2005-12-01</dob>
            <Jyear>2023</Jyear>
        </student>
    </students>
